### ISSUE TITLE
Update their_knowledge (**) on consensus on receiving an AckMessage from that section

### ISSUE THREAD

**Issue by nadiaburborough** [maidsafe/routing#1670]
=> On consensus on an AckMessage
=> Note: AckMessage is sent on receiving a message from a section where the SectionProofChain contained in that message has len > 1

Dependent on https://github.com/maidsafe/routing/issues/1673

**Comment by jeanphilippeD** [comment]
When receiving an AckMessage, vote for a new NetworkEvent that contains the needed information for all peers to update `their_knowledge` on consensus from their shared state: SectionInfo / Signatures / Proof that signature are valid decendants from the one we know in `their_keys`.
On consensus, Update `their_knowledge` after verifying validity (Should always be valid unless malice).
Like currently existing Proving sections, a single vote is needed to accumulate.

(We probably should split into 2 PR: 1 - Add NetworkEvent containing only SectionInfo, and implicitly trust these AckMessage consensus are valid and update the their_knowledge accordingly. 2 - Add necessary info to consensused event so all peers can validate trust.)

**Comment by jeanphilippeD** [comment]
The second part of this issue is no longer needed:
> 2 - Add necessary info to consensused event so all peers can validate trust.)

The AckMessage is a section signed message. Section signed message always contain sufficient proof for all nodes at the destination to validate them since PR #1739 

As a result, we do not need to add additional information to the consensused event beside that it was received as a message that was trusted by the 2/3 quorum (which it will have since the destination is a section so all node will get the messages).

@maqi @fizyk20 
Could you both confirm and I'll close this issue as done.

**Comment by jeanphilippeD** [comment]
Closing as per https://github.com/maidsafe/routing/issues/1670#issuecomment-525751754
