### ISSUE TITLE
Resend messages on failure (how does routing pick the new recipient?)

### ISSUE THREAD

**Issue by Lindsey17** [maidsafe/routing#1684]
=> When receiving send_failure from the networking layer, routing will need to pick a different relay target

=> The destination may be picked based on state we have when receiving failure. We may need to maintain some cached info abt the member state when attempting to send the msg…

Dependent on https://github.com/maidsafe/routing/issues/1681

**Comment by dirvine** [comment]
RMD works this out all we need do is return the message on failure. RMD should select the next candidate for the message.

**Comment by jeanphilippeD** [comment]
@dirvine Did you have something specific in mind for selecting the next candidate to resend.
Did that involve LruCache (to cache data but only receive notification of failure not success)?
Does that mechanism handle receiving section splitting? or receiving node going offline?

We are discussing scheme to implement it currently, but if you had something specific please let us know.

**Comment by dirvine** [comment]
Not really on failure from the send we would select the `f+2`nd candidate if 2 sends fail then we also select the `f+3`rd candidate and so on. The way I would do this is probably as a transaction, where the `f+1` candidates are in a transaction and any error we select the next candidate. I would not think we need a lru cache or similar as it seems too much. 
I have not done a POC for the failure case though, it may be more complex, but I am thinking it would be relatively simple. I think the code with async/await would be simpler. So await each send and any error select the next candidate in this transaction (which is basically `f+1` send() functions). 
I hope that makes sense.

**Comment by pierrechevalier83** [comment]
We had a discussion in slack and this is where we're currently standing for the design (may still evolve)
1. When sending a message to some targets, add an entry in the cache with key = msg hash, value = map of target statuses. All targets have their status initialised to `Sending(0)`.
2. When we get a failure from a target:
  - change the status to `Failed(status.0+1)`
  - request a new target from the chain; pass the list of all targets that have been tried so far map of status, so that the chain knows which one would be new and less tried
  - send to that new target
3. The cache would be an `LruCache`; if there were no failures for a time, a message would naturally get ejected from the cache.
4. If we receive a failure for a message that is not in the cache, ignore it: this means that it was already ejected.

**Comment by pierrechevalier83** [comment]
Picking up this task for now as @fizyk20 will be on holiday for a week.

**Comment by jeanphilippeD** [comment]
This is the last version we discussed on slack:
This flow should be a reasonable aggregate of all ideas for RMD resend (Probably have its own issue).

The 2 main thing it address, which I think is important, is
 - Ensure that all 3 targets where at some point the Elder of a single section.
 - At the same time simplifying by avoiding going back to the chain: ignore PublicId, only use quick-p2p connection info (SocketAddr): not impacted by us forgetting a Peer PublicId.

When sending a message:
1. Retrieve the set of potential targets for a message ordered by priority, with delivery_group_size.
   Convert the potential targets from PublicId to SocketAddr (no problem if peer is gone, can handle failure and resend).
   Add an entry in the cache with key = msg hash, value = MsgDelivery{potential_targets_ordered_by_priority_addr, map_of_target_statuses}
   (MsgDelivery may be implemented anyway that is most optimal and easy, could use a next_target_idx if useful, could use Rc at some point).
   Initialized all targets status to Failed(0).
   Take first delivery_group_size targets in potential_targets_ordered_by_priority_addr and send message:
2. Send Message:
    Set Target status to Sending(status.0)
3. When we get a CanNoLongerGetFalure from a target:
  - change the status to `Sent`
4. When we get a failure from a target:
  - change the status to `Failed(status.0+1)`
  - Find in potential_targets_ordered_by_priority_addr the first target not `Sending` or `Sent`, and with min `Failed(status)`.
  - If Failed(status < MAX_RESEND) send to that new target, otherwise drop it.
    (Need to drop especially if we target a single node on final hop and that node is gone.)

Cons:
- if too many peers in potential_targets_ordered_by_priority can never be connected too, we won't be able to send the message to delivery_group_size targets, but that should not happen with our assumption of less than 1/3 faulty nodes.

Pros:
- Guarantee that all chosen target were at some point in the same section, so we expect one of these to be non faulty/malicious, and forward the message to the next hop, even if a split occur and they are now in 2 different sections.
- Not impacted by change in the Peer we "know" as we will keep sending and responding to error even if the peer is no longer known in Routing.

**Comment by fizyk20** [comment]
Sorry for the mess above, clicked the wrong button by mistake :sweat_smile:
