### ISSUE TITLE
Handling of messages addressed to the previous section of a relocated node

### ISSUE THREAD

**Issue by madadam** [maidsafe/routing#1901]
Sometimes a node gets relocated, but is still considered part of the delivery group of its original section. We currently ignore such messages but that sometimes causes issues:

- If the relocated node was part of the `src` authority, the signature accumulation might fail
- If the relocated node was part of the `dst` authority, then it might think it's just supposed to relay the message to a section that is closer to `dst` which might happen to be `src` - but `src` has seen the message, so it would filter it out. For example: There are sections `00`, `01` and `100`. A node gets relocated from `01` to `100`. A message is sent from `00` to `01`, but it is handled by the relocated node. As it is not part of `dst` anymore, it relays the messages closer to `dst`. Closest section to `01` it knows is `00` which is the section that originally sent the message.

Failing test case that shows the above situation:
test: `aggressive_churn`
commit: `de008b2c8`
seed: `[277475111, 4073174972, 2973065267, 3524148088]`

Possible solutions:

1. Delay node relocation: When an elder is relocated, it should stay in the original section (just demoted to adult, or possibly in some kind of special in-between state) and only move to the target section either after some time or based on some other condition.
2. Relocated node should somehow bounce those messages back so the sender can resend them. 
3. Other?

**Comment by dirvine** [comment]
I think it may be OK, if the rule is you always send the message closer then I think we are OK. Even if it went back to src
In this kind edge case of going back to src, then the problem is the message filter. I reckon this is the issue really. Perhaps thinking around this would be better? Perhaps add the section prefix to each message as we forward it? Then OK to filter and if there is a split the prefix is changed, so still OK?
So message itself is not tampered with, but we just have that append/prepended prefix, in some throw away mechanism?

**Comment by madadam** [comment]
Delayed relocation implemented in #1929 and it seems to be working fine so far. Closing.
