### ISSUE TITLE
routing_node::run() needs to be internal to routing

### ISSUE THREAD

**Issue by chandraprakash** [maidsafe/routing#202]
Routing::run() needs to be internal to routing and upper layer should not have any control on this. This should be called inside bootstrap method (non public method). This method allows routing to accept messages from crust. Same applies to routing client separate task (https://github.com/dirvine/routing/issues/204).

**Comment by maqi** [comment]
I think you mean RoutingNode::run() here?
There was discussion of spawning inside RoutingNode or RoutingClient,
and it turns out to be not a easy task to do in rust.
i.e. all the mutable components currently in RoutingNode or RoutingClient need to be wrapped into a mutex struct, similar to what used in ConnectionManager.
it will be no different to the current structure except the holder of the spawning thread moved from routing to RoutingNode or RoutingClient,
however the code in RoutingNode or RoutigClient need to be heavily refactored and may become more complicated.

**Comment by chandraprakash** [comment]
Myself and Peter had a discussion on this approach. We didn't reach a conclusion. And this task was then deferred till end of this iteration.

**Comment by benjaminbollen** [comment]
This issue will be picked up in https://maidsafe.atlassian.net/browse/MAID-1057

As mentioned in #221 #204 it is important that we resolve to not using mutexes.  A single thread should own a single mutable state.

**Comment by benjaminbollen** [comment]
task completed
