### ISSUE TITLE
Have the threshold in BLS set at PARSEC quorum (at min over 50% to prevent double-voting etc.)

### ISSUE THREAD

**Issue by S-Coyle** [maidsafe/routing#2045]

**Comment by jeanphilippeD** [comment]
Considerations for changing the BLS threshold for the section Key:

- During the DKG, elements are encrypted to destinations. So malicious node can use response that only a subset of good nodes can use. 
 - To complete a DKG, we need to ensure that threshold good node responses are taken into account.
 - Currently we have both the requirement that 1/3 of response may come from malicious node and 1/3 of (malicious node may not respond). This guarantee both that the DKG will complete in presence of malice, and also that the DKG will yield a good key.

In order to handle threshold greater that 1/3, we need to accept that either 1/3 malicious node may stall the DKG, or some node do not have a good key if malice occured, or both.

One approach to address this is handling the no guarantee of completing:
 - Parsec stop guaranteeing completion of DKG, Routing start another DKG until one complete.
   => Currently no information leak outside of Parsec about what happened in DKG so we probably will need something here.
   => Probably, if DKG does not succeed in time, a new vote could force it to complete giving the missing responses, so the misbehaving node can be removed.
 - With that approach, one can tweak threshold from 1/3 to 2/3, by eating up the number of node that we can allow not to respond "in time".


The other approach, I think is also possible, is to allow malicious nodes to participate, and that mean that the key if produced may not be correct for all nodes, I think there may be a way to prove it thus discarding the malicious node afterward and redoing DKG again. That may be quite a bit trickier.



Either approach means that we now have to handle in our ElderChange flow the possibility that the initial elders we choose may not succeed in finishing the DKG and we need to change to another set. so this add complexity to this flow, and also all the code needed to pass along errors.

**Comment by dirvine** [comment]
https://github.com/dashpay/dips/blob/master/dip-0006/bls_m-of-n_threshold_scheme_and_dkg.md#distributed-key-generation-dkg-protocol

**Comment by jeanphilippeD** [comment]
Second set of consideration:
 - it is possible to increase the threshold of the resulting key without requiring higher security, or change in the algorithm and its constraints. Essentially we can create any threshold (which could be over 50% and would avoid the related problem without increasing the security property).

The original discussion was here : https://maidsafe.slack.com/archives/C03DZQTKU/p1559729671099600?thread_ts=1559566842.094800&cid=C03DZQTKU

**Comment by jeanphilippeD** [comment]
My recommendation:

First Read the original discussion mentioned in previous comment for context and pitfalls.

The cleaner option would be to "[extend threshold_crypto with non-symmetric polynomials](https://maidsafe.slack.com/archives/C03DZQTKU/p1559729558098000?thread_ts=1559566842.094800&cid=C03DZQTKU)" which "[Shouldn't be a difficult change to make](https://maidsafe.slack.com/archives/C03DZQTKU/p1559729611098800?thread_ts=1559566842.094800&cid=C03DZQTKU)". It would then give full freedom to set the BLS threshold independently of the DKG threshold. **However I have no personal idea of what this change involve.**

So if we only need to implement a 2/3 BLS threshold, I would opt for the simpler, for a programmer. option:  `sending double the number of Parts/Acks` described bellow: This give you a BLS threshold of 2f, so require 2f+1 signatures share to produce valid signature (i.e 66.6%):

Changes to Parsec: src/key_gen/mod.rs
- The square BivarPoly is created twice as big as the threshold.
- Each Parts contain 2 rows encrypted to us and are treated together.
- Each Ack contains 2 items, 1 from each of the 2 rows in the corresponding Part, encrypted to us and are treated together.
- At the end we received the same number of Parts/Acks as in the existing implementation, and when we received 2t+1 Acks, we combine the 2 * (2t+1) elements to reconstruct the secret BLS key share and public BLS keys requiring 2*t+1 signature share to be valid.

```
/// A submission by a validator for the key generation. It must to be sent to all participating
/// nodes and handled by all of them, including the one that produced it.
///
/// The message contains a commitment to a bivariate polynomial, and for each node, (NOT ONE BUT) TWO encrypted
/// row of values. If this message receives enough `Ack`s, it will be used as summand to produce
/// the the key set in the end.
#[derive(Deserialize, Serialize, Clone, Hash, Eq, PartialEq, PartialOrd, Ord)]
pub struct Part(BivarCommitment, Vec<Vec<u8>>);

// Use 2 * threshold (= 2 * 1/3 of N)
let our_part = BivarPoly::random(2 * threshold, &mut rng);

/// A confirmation that we have received and verified a validator's part. It must be sent to
/// all participating nodes and handled by all of them, including ourselves.
///
/// The message is only produced after we verified our (NOT ONE BUT) TWO row against the commitment in the `Part`.
/// For each node, it contains one encrypted value of that (NOT ONE BUT) TWO rows.
#[derive(Deserialize, Serialize, Clone, Hash, Eq, PartialEq, PartialOrd, Ord)]
pub struct Ack(u64, Vec<Vec<u8>>);
```

**Comment by madadam** [comment]
The new DKG implementation uses 2/3 quorum, which might be changed to 1/2 later. Closing.
