### ISSUE TITLE
Simplify the xor_space module

### ISSUE THREAD

**Issue by madadam** [maidsafe/routing#2129]
Currently it's unnecessarily complex because it's too generic. There is no need for the genericity as we only really use the `XorName` type. The other types are used only in tests where they could relatively easily be replaced by `XorName`. We should also remove the generic parameter from `Prefix`.

**Comment by S-Coyle** [comment]
Note that since this issue was created the [xor-name](https://github.com/maidsafe/xor-name) repo has been restored from archive with the intention of removing ir from routing - once that is complete, this issue may need transferred to the xor-name repo.

Added task to shared `Spare Time Work` project board

**Comment by dirvine** [comment]
Moved to xor_name crate now. Perhaps we can update the board @S-Coyle and close this issue here?

**Comment by madadam** [comment]
Already addressed in https://github.com/maidsafe/xor-name. Closing.
