### ISSUE TITLE
Call to RoutingClient from maidsafe-client crate panics

### ISSUE THREAD

**Issue by ustulation** [maidsafe/routing#277]
For example calling unauthorised-put causes:
```
stack backtrace:
   1:     0x7fc77fd7cfb9 - sys::backtrace::write::he19dad14fe2b97b1w6r
   2:     0x7fc77fd807b9 - panicking::on_panic::h330377024750b34dHMw
   3:     0x7fc77fd729c2 - rt::unwind::begin_unwind_inner::h7703fc192c11eec8Rrw
   4:     0x7fc77fd73407 - rt::unwind::begin_unwind_fmt::hc8ceb80825e565b5Xqw
   5:     0x7fc77fd80446 - rust_begin_unwind
   6:     0x7fc77fdafa44 - panicking::panic_fmt::hd5126a261e0825dcw1B
   7:     0x7fc77fdacf14 - panicking::panic::hb15daac79dd1426d3ZB
   8:     0x7fc77fc93782 - option::Option<T>::unwrap::h11414150206363110167
                        at /home/rustbuild/src/rust-buildbot/slave/nightly-dist-rustc-linux/build/src/libcore/macros.rs:19
   9:     0x7fc77fc99178 - routing_client::RoutingClient<F>::unauthorised_put::h6515338189982331746
                        at /home/spandan/.cargo/registry/src/github.com-1ecc6299db9ec823/routing-0.1.60/src/routing_client.rs:248
  10:     0x7fc77fc6aac5 - client::Client::create_account::h0e056ba21158e7f15sc
                        at src/client/mod.rs:70
  11:     0x7fc77fcaa602 - client::test::account_creation::h698ab215c64c7a40lAc
                        at src/client/mod.rs:188
  12:     0x7fc77fccdfdb - boxed::F.FnBox<A>::call_box::h10806636898263112044
  13:     0x7fc77fcd10d7 - boxed::F.FnBox<A>::call_box::h7348684160606361188
  14:     0x7fc77fcce7c9 - rt::unwind::try::try_fn::h13513740954489387225
  15:     0x7fc77fd85938 - rust_try_inner
  16:     0x7fc77fd85925 - rust_try
  17:     0x7fc77fd7b0b7 - rt::unwind::try::inner_try::hb6f04bd1baacc20eKnw
  18:     0x7fc77fcce9fa - boxed::F.FnBox<A>::call_box::h6754105881859822973
  19:     0x7fc77fd7f5e1 - sys::thread::Thread::new::thread_start::h285dd80d49b81cf50xv
  20:     0x7fc77eca1181 - start_thread
  21:     0x7fc77f4bb47c - __clone
  22:                0x0 - <unknown>
```

calls to put/run etc also panic.

**Comment by benjaminbollen** [comment]
when running maidsafe_client I currently have a build error:

``` Compiling maidsafe_client v0.0.1 (file:///home/bbollen/SAFE/rust/maidsafe_client)
src/client.rs:25:5: 25:26 error: unresolved import `routing::RoutingError`. There is no `RoutingError` in `routing`
src/client.rs:25 use routing::RoutingError;```
                     ^~~~~~~~~~~~~~~~~~~~~

**Comment by benjaminbollen** [comment]
so there is for sure a panic in routing

Ben B [2:17 PM]
but maidsafe_client::Client::create_account creates a new routing_client (should it?) and there is no network to connect to

Ben B [2:18 PM]
so a test written like that is written to fail, right?

Ben B [2:18 PM]
it is an issue that we need to address, routing should never panic!, but I don't see how the test will pass

Spandan Sharma [2:27 PM] 
Should not routing start networking when i create a new instance of routing_client

Spandan Sharma [2:27 PM]
If i don't create a new routing_client, what is the alternative

Ben B [2:35 PM] 
that is a legitimate question: I would argue that a best approach is that the private functions are testable on their logic disconnected from a newtork

Ben B [2:35 PM]
because the get and put logic should be able to be factored out

Ben B [2:36 PM]
starting a client does not start nodes

Ben B [2:36 PM]
and more importantly, storing your keys should maybe use an existing client

Ben B [2:37 PM]
and as such you can have a dummy_client in tests, that can get and put to local memory

Ben B [2:37 PM]
that way the NFS and self_authentication logic is tested independently from a routing network

**Comment by benjaminbollen** [comment]
Will be addressed in https://maidsafe.atlassian.net/browse/MAID-1062

**Comment by benjaminbollen** [comment]
should be resolved; create new issue if other panic occurs
