### ISSUE TITLE
Clean up debug option

### ISSUE THREAD

**Issue by rossmuir** [maidsafe/routing#721]
With `RUST_LOG=debug` ON you see very these long number lists (example below), these make finding patterns difficult - is it possible to suppress these? 

```
DEBUG:routing::routing_node: Sending InternalRequest(Refresh(3, [162, 100, 110, 97, 109, 101, 152,
64, 24, 186, 24, 95, 24, 234, 24, 218, 24, 102, 24, 122, 24, 193, 9, 24, 162, 24, 132, 9, 24, 45, 24,
186, 24, 204, 24, 220, 24, 253, 24, 93, 24, 197, 24, 31, 24, 96, 24, 151, 24, 128, 24, 62, 8, 24, 115,
24, 249, 24, 54, 24, 49, 24, 189, 24, 75, 24, 199, 24, 253, 24, 73, 24, 186, 24, 199, 24, 106, 24, 184,
24, 55, 24, 161, 24, 208, 12, 24, 211, 24, 237, 24, 216, 24, 157, 24, 104, 24, 171, 24, 131, 24, 158,
24, 164, 24, 127, 24, 211, 24, 247, 24, 56, 24, 100, 24, 140, 24, 139, 24, 108, 24, 50, 24, 36, 24, 136,
24, 240, 24, 47, 24, 36, 110, 114, 101, 115, 111, 117, 114, 99, 101, 95, 105, 110, 100, 101, 120, 0],
c87df5..5c0755)) to 8 target connection(s)
```

**Comment by canndrew** [comment]
Instead of using `Vec<u8>` everywhere for serialised data we could wrap it in something like:

    struct Bytes(pub Vec<u8>);

And then `impl Debug for Bytes` so that it prints `Bytes [0xa2 0x64 ... 0x78 0x00]` or something of the sort. Alternatively we could wrap the `Vec` like this:

    struct Serialised<T> {
        data: Vec<u8>,
        _pd: std::marker::PhantomData<T>,
    }

This has the advantage of being slightly more type-safe (you can't confuse a `Serialised<A>` for a `Serialised<B>`). It would also let us define an `impl<T: Debug> Debug for Serialised<T>` that deserialises the data and prints the result (although that might be overkill).

**Comment by Fraser999** [comment]
I agree here too, and have a slight preference for the latter option, which is really a fleshed-out version of what I was thinking of in [my other comment](https://github.com/maidsafe/routing/issues/723#issuecomment-144752640) about `NameType`.

From previous experience, the `Serialised<T>` technique can easily become over-used.  I think from the perspective of taming the debug output it's useful, but I think we should try and avoid creating too many different types of `Serialised<T>` as far as possible.

**Comment by benjaminbollen** [comment]
duplicates #722

**Comment by canndrew** [comment]
FWIW you can selectively enable debug output for certain modules/functions using the [`RUST_LOG` environment variable](https://doc.rust-lang.org/log/env_logger/index.html).
