### ISSUE TITLE
Vault starts failing CI checks after routing/crust updated

### ISSUE THREAD

**Issue by maqi** [maidsafe/routing#728]
This is as described in https://maidsafe.atlassian.net/browse/MAID-1387,
after routing/crust version bumped, Vault's starts failing CI checks (check https://travis-ci.org/maidsafe/safe_vault/builds/82599916 and https://ci.appveyor.com/project/MaidSafe-QA/safe-vault/build/1.0.191 for the failing details)

If it turns out not due to an issue from routing, please notify correspondent lib maintainer.

**Comment by maqi** [comment]
After the network tests have been modified to be merged into one test (only need to setup the network environment once), the dropping of routing_node issue still failing the test, both on local machines or on the CI machines.

Some error messages can be observed such as : 
https://travis-ci.org/maidsafe/safe_vault/jobs/84888221#L1145-L1172
https://travis-ci.org/maidsafe/safe_vault/jobs/84888222#L996

**Comment by benjaminbollen** [comment]
is it possible to get more debug output, or is that not possible because of the way it set up with different processes?  It is not clear to me what goes wrong, to find out I'd have to debug vaults.  The printed error happens when the channel to the user is already broken.  Does vaults destroy the event_receiver possibly?

**Comment by maqi** [comment]
The debug output is not enabled in CI scripts.
I tried to run the test locally with debug output, however, once Debug is switched on, the issue gone so far (tried over ten times).   :(

Vault won't destroy any event_receiver, as I know.
